[project]
name = "Alinka"
description = "Application for Supporting Center for Children"
authors = [{name = "CodeForPoznań", email = "hello@codeforpoznan.pl"}]
license = {text = "MIT"}
# base, ignored, version, that's required by Poetry
# we will provide proper verion dynamically to our build pipelines
version = "0.0.0"
dynamic = ["version"]

[tool.poetry.dependencies]
Jinja2 = "^3.1.4"
pydantic = "2.9.2"
PySide6 = "6.8.3"
python = "3.10.9"
SQLAlchemy = "2.0.4"
pydantic-settings = "^2.5.2"
alembic = "^1.13.2"
requests = "^2.32.3"
platformdirs = "^4.3.6"
sqlcipher3-binary = "^0.5.4"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
factory-boy = "^3.2.1"
faker = "^18.4.0"
flake8 = "^5.0.4"
flake8-pyproject = "^1.2.3"
isort = "^5.10.1"
pyinstaller = "^5.10.1"
pytest = "^7.2.0"
cairosvg = "^2.7.1"
pillow = "^11.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.venv
  | build
  | dist
)/
'''

[tool.flake8]
max-line-length = 120
extend-ignore = ["E203"]

[tool.isort]
profile="black"

[tool.pytest.ini_options]
pythonpath = ["."]
